inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rake'
  Exclude:
    - .bundle/**/*
    - db/schema.rb
    - features/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/locale/*
    - package/*
