language: ruby
rvm:
  # SLES15 sp0
  - 2.4.1

  # Future versions
  - ruby-head
script:
  - 'bundle exec rails db:migrate RAILS_ENV=test'
  - 'bundle exec rspec spec'
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE rmt_test;" -U postgres
  - psql -c "CREATE USER rmt WITH PASSWORD 'rmt';" -U postgres
  - psql -c "grant all privileges on database rmt_test to rmt;" -U postgres
