language: ruby
rvm:
  # SLES15 sp0
  - 2.4.1

  # Future versions
  - ruby-head
script:
  - 'bundle exec rails db:migrate RAILS_ENV=test'
  - 'bundle exec rspec spec'
  - 'bundle exec rubocop'
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE potato_test;" -U postgres
  - psql -c "CREATE USER potato WITH PASSWORD 'potato';" -U postgres
  - psql -c "grant all privileges on database potato_test to potato;" -U postgres
