version: '2'
volumes:
  db_storage:
    driver: local

services:
  db:
    extends:
      service: base
      file: docker-compose-base.yml
    image: registry.scc.suse.de/postgresql:9.4
    volumes:
      - db_storage:/var/lib/pgsql/data

  rmt:
    extends:
      service: base
      file: docker-compose-base.yml
    build: .
    environment:
      - RAILS_ENV=test
      - POSTGRES_HOST=db
    volumes:
      - ./:/srv/www/potato
    depends_on:
      - db
    command: bash -c 'bundle exec rails db:migrate && bundle exec rails s'

  nginx:
    image: nginx
    volumes:
      - ./public:/var/www/
      - ./nginx/ca.pem:/var/www/rmt.pem
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - rmt
