version: '2'
volumes:
  db_storage:
    driver: local

services:
  db:
    extends:
      service: base
      file: docker-compose-base.yml
    image: postgres
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  rmt:
    extends:
      service: base
      file: docker-compose-base.yml
    build: .
    environment:
      - POSTGRES_HOST=db
      - RAILS_ENV=production
    depends_on:
      - db
    command: bash -c 'bundle exec rails db:migrate && bundle exec rails s -b rmt'
    ports:
      - 3000:3000

  nginx:
    image: nginx
    volumes:
      - ./public:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - rmt
