# This is development configuration.
# Production configuration that is shipped in the RPM package can be found in /package/rmt.conf.
# You can create rmt.local.yml to override settings in this file.

database: &database
  host: localhost
  database: rmt
  username: rmt
  password: rmt
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  pool: 5

database_development:
  <<: *database
  database: rmt_development

database_test:
  <<: *database
  database: rmt_test

scc:
  username:
  password:

mirroring:
  mirror_src: false
  verify_rpm_checksums: false

rails:
  port: 4224

cli:
  user: _rmt
  group: nginx

http_client:
  verbose: false
  proxy:
  proxy_auth:
  proxy_user:
  proxy_password:

