mirroring:
  base_dir: /srv/www/repo/
  mirror_url_prefix: /repo/
  mirror_src: false
  verify_rpm_checksums: false

http_client:
  verbose: false
  proxy:
  proxy_auth:
  proxy_user:
  proxy_password:

scc:
  username:
  password:
